package Beginner;

import java.util.Random;
import java.util.Scanner;

public class RandomGuessGame {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random random = new Random();
		boolean valid = false, game = true;
		int diff;
		int randomint;
		int guesslimit, guess = 0, answer;
		Scanner scan = new Scanner(System.in);
		boolean again = true; char yes;
		
		do {
		System.out.println("Welcome to RandomGuessGame. Guess the random number generated by the machine!");

		do {
			System.out.println("Please select difficulty: Easy = 1, Intermediate = 2, Hard = 3 ");
			diff = scan.nextInt();
			if (diff >= 1 && diff <= 3) {
				valid = true;
			} else {
				System.out.println("Invalid difficulty level.");
			}
		} while (!valid);

		switch (diff) {

		case 1:
			System.out.println("Easy level: Guess the number between 0 and 10. Guess limit is only 3.");
			randomint = random.nextInt(10);
			guesslimit = 3;
			do {
				System.out.println("Please input your guess:");
				answer = scan.nextInt();
				if (answer == randomint) {
					guess++;
					System.out.println("You are right! Congratulations! it took you " + guess + " guesses.");
					break;
				}
				if (answer > randomint) {
					System.out.println("Lower...");
					guess++;
				} else {
					System.out.println("Higher...");
					guess++;
				}
				if (guess == guesslimit) {
					System.out.println("Tough luck! Try again later. The answer is " + randomint);
				}
			} while (guess != guesslimit);
			break;
		case 2:
			System.out.println("Intermediate level: Guess the number between 0 and 50. Guess limit is only 7.");
			randomint = random.nextInt(50);
			guesslimit = 7;
			do {
				System.out.println("Please input your guess:");
				answer = scan.nextInt();
				if (answer == randomint) {
					System.out.println("You are right! Congratulations! it took you " + guess + " guesses.");
					break;
				}
				if (answer > randomint) {
					System.out.println("Lower...");
					guess++;
				} else {
					System.out.println("Higher...");
					guess++;
				}
				if (guess == guesslimit) {
					System.out.println("Tough luck! Try again later. The answer is " + randomint);
					game = false;
				}
			} while (guess != guesslimit);
			break;
		case 3:
			System.out.println("Hard level: Guess the number between 0 and 100. Guess limit is only 10.");
			randomint = random.nextInt(100);
			guesslimit = 10;
			do {
				System.out.println("Please input your guess:");
				answer = scan.nextInt();
				if (answer == randomint) {
					System.out.println("You are right! Congratulations! it took you " + guess + " guesses.");
					break;
				}
				if (answer > randomint) {
					System.out.println("Lower...");
					guess++;
				} else {
					System.out.println("Higher...");
					guess++;
				}
				if (guess == guesslimit) {
					System.out.println("Tough luck! Try again later. The answer is " + randomint);
					game = false;
				}
			} while (guess != guesslimit);
			break;
		}
		System.out.println("Do you want to play again?");
		yes = scan.next().charAt(0);
		if (yes == 'y' || yes=='Y') {
			guess = 0;
			game = true;
		}
		else {
			game= false;
			scan.close();
			return;
		}
		}
		while(game == again);

		
	}

}
